import React, { useState } from 'react'
import { createRoot } from 'react-dom/client'
import { Search, PanelLeftClose, PanelLeftOpen, Plus, MessageSquare, FileText, CircleCheck, Users, BarChart3, ChevronRight, Pencil, Paperclip, Send, Check, Info, Sparkles, CalendarDays, CircleDollarSign, ListChecks, Clock3, Menu, X, type LucideIcon } from 'lucide-react'
import './styles.css'

type Flow = 'business' | 'manager' | 'procurement'
type RequestData = { requestType:string; service:string; location:string; employees:string; targetDate:string; personalData:string; personalDataDetail:string; notes:string; budget:string; criteria:string; deadline:string }
type ChatMessage = { id:number; author:'user'|'ai'; text:string }

const initialRequest:RequestData = { requestType:'New supplier', service:'Travel management services', location:'France', employees:'~500 employees', targetDate:'2027-01-01', personalData:'Yes', personalDataDetail:'Traveller names, contact details, booking information', notes:'Include 24/7 support', budget:'€800k–€1M annually', criteria:'Price, service coverage, implementation and security', deadline:'2026-09-30' }
const screens:Record<Flow,string[]> = {
  business:['Dashboard','Prompt entered','Intake · collapsed','Intake · overview','Draft generated','Draft updated','Edit information','Confirm submission','Request details'],
  manager:['Dashboard','Prompt entered','Review · collapsed','Review · overview','Add documents','Send confirmation','Request sent','Edit information'],
  procurement:['Dashboard','Prompt entered','Request overview','Analysis','Edit information','Saved','Information needed','Send confirmation','Request sent'],
}

function App(){
  const [flow,setFlow]=useState<Flow>('business'), [step,setStep]=useState(0), [sidebarOpen,setSidebarOpen]=useState(true), [overviewOpen,setOverviewOpen]=useState(true)
  const [request,setRequest]=useState<RequestData>(initialRequest), [documents,setDocuments]=useState(['Travel_Policy.pdf','Approval_Email.pdf']), [messages,setMessages]=useState<ChatMessage[]>([]), [toast,setToast]=useState('')
  const max=screens[flow].length-1, go=(next:number)=>setStep(Math.max(0,Math.min(next,max)))
  const notify=(text:string)=>{setToast(text);window.setTimeout(()=>setToast(''),2400)}
  const changeFlow=(next:Flow)=>{setFlow(next);setStep(0);setMessages([]);setOverviewOpen(true)}
  const openRequest=()=>go(flow==='business'?8:flow==='manager'?6:8), editStep=flow==='business'?6:flow==='manager'?7:4
  const startFromPrompt=(text:string)=>{if(!text.trim())return;setMessages(v=>[...v,{id:Date.now(),author:'user',text:text.trim()}]);go(step===0?1:2)}
  const sendMessage=(text:string)=>{const clean=text.trim();if(!clean)return;setMessages(v=>[...v,{id:Date.now(),author:'user',text:clean},{id:Date.now()+1,author:'ai',text:responseFor(clean,flow)}]);if(/edit|change|update|incorrect/i.test(clean))go(editStep);else if(step<max)go(step+1)}
  const person=flow==='business'?'John Dupont':'Catherine Moreau', role=flow==='business'?'Business Manager':flow==='manager'?'Contract Manager':'Procurement Manager'
  return <div className={`app-shell ${!sidebarOpen?'sidebar-closed':''} ${step<2||!overviewOpen?'overview-closed':''}`}>
    <button className="mobile-menu" onClick={()=>setSidebarOpen(v=>!v)} aria-label="Toggle navigation"><Menu/></button>
    {!sidebarOpen&&<button className="open-sidebar" onClick={()=>setSidebarOpen(true)} aria-label="Open navigation"><PanelLeftOpen/></button>}
    {sidebarOpen&&<Sidebar flow={flow} person={person} role={role} onCollapse={()=>setSidebarOpen(false)} onNew={()=>go(0)} onNavigate={destination=>{if(destination==='request')openRequest();else if(destination==='new')go(0);else notify(`${destination} opened in prototype mode`)}}/>}
    <main className="workspace"><FlowTabs flow={flow} step={step} setFlow={changeFlow} setStep={go}/>{step<2?<Home flow={flow} step={step} onSend={startFromPrompt} onAttach={()=>notify('Attachment option opened')}/>:<Conversation flow={flow} step={step} go={go} request={request} setRequest={setRequest} documents={documents} setDocuments={setDocuments} messages={messages} onSend={sendMessage} notify={notify}/>}</main>
    {step>=2&&overviewOpen&&<Overview flow={flow} step={step} request={request} documents={documents} onClose={()=>setOverviewOpen(false)} onEdit={()=>go(editStep)} onOpenRequest={openRequest}/>}
    {step>=2&&!overviewOpen&&<button className="open-overview" onClick={()=>setOverviewOpen(true)}>Overview <PanelLeftOpen/></button>}
    {toast&&<div className="toast" role="status"><CircleCheck/>{toast}</div>}
  </div>
}

function responseFor(text:string,flow:Flow){if(/document|attach|file/i.test(text))return'I can help attach the supporting documents. Opening the document step now.';if(/edit|change|update|incorrect/i.test(text))return'Of course. I’ve opened the request fields so you can make the changes.';if(/status|detail/i.test(text))return'Here is the latest request status and the information recorded so far.';if(/submit|send|confirm|continue/i.test(text))return flow==='business'?'I’ll prepare the request for submission.':'I’ll move the request to its next review stage.';return'Thanks. I’ve recorded that and updated the conversation.'}

function FlowTabs({flow,step,setFlow,setStep}:{flow:Flow;step:number;setFlow:(v:Flow)=>void;setStep:(v:number)=>void}){return <nav className="prototype-nav" aria-label="Prototype screen navigation"><label>Prototype flow<select value={flow} onChange={e=>setFlow(e.target.value as Flow)}><option value="business">Business Owner</option><option value="manager">Contract Manager</option><option value="procurement">Procurement</option></select></label><label>Screen<select value={step} onChange={e=>setStep(Number(e.target.value))}>{screens[flow].map((name,i)=><option value={i} key={name}>{i+1}. {name}</option>)}</select></label></nav>}

function Sidebar({flow,person,role,onCollapse,onNew,onNavigate}:{flow:Flow;person:string;role:string;onCollapse:()=>void;onNew:()=>void;onNavigate:(v:string)=>void}){
  const nav:Array<[string,LucideIcon,string]>=flow==='business'?[['My requests',MessageSquare,'request'],['Contracts',FileText,'Contracts'],['Approvals',CircleCheck,'Approvals']]:[['Approvals',CircleCheck,'Approvals'],['Contracts',FileText,'Contracts'],['My requests',MessageSquare,'request'],['Supplier',Users,'Supplier workspace'],['Insights',BarChart3,'Insights']]
  const recents=['REQ-2026-0187','Renewal review - Cloud','Supplier onboarding','Clause clarification','Risk review - Data privacy']
  return <aside className="sidebar"><header className="brand"><div className="sg-mark"><i/>SOCIETE<br/><span>GENERALE</span></div><button aria-label="Search requests" onClick={()=>onNavigate('Search')}><Search/></button><button aria-label="Collapse sidebar" onClick={onCollapse}><PanelLeftClose/></button><small>Contract Lifecycle Management</small></header><button className="new-chat" onClick={onNew}><Plus/> New chat</button><nav className="side-nav">{nav.map(([label,Icon,destination])=><button key={label} onClick={()=>onNavigate(destination)}><Icon/>{label}{label==='Approvals'&&<b>2</b>}</button>)}</nav><section className="recents"><h3>⌄ &nbsp; RECENTS</h3>{recents.map((item,i)=><button className={i===0?'active':''} key={item} onClick={()=>onNavigate(i===0?'request':item)}><MessageSquare/><span>{item}<small>{i===0?'Today, 10:24':i===1?'Yesterday, 15:10':`${12-i*2} Sep 2026`}</small></span></button>)}</section><footer><span className="avatar">{person.split(' ').map(v=>v[0]).join('')}</span><span>{person}<small>{role}</small></span><button aria-label="Profile options" onClick={()=>onNavigate('Profile options')}>•••</button></footer></aside>
}

function Home({flow,step,onSend,onAttach}:{flow:Flow;step:number;onSend:(v:string)=>void;onAttach:()=>void}){
  const [text,setText]=useState(flow==='business'?'I need a new travel management supplier for our France offices':'Review supplier request REQ-2026-0187')
  const suggestions=flow==='procurement'?['Review this supplier contract','Compare this amendment','Amend an existing contract','Review supplier requests']:flow==='manager'?['Review supplier requests','Follow up on information','Renew or extend a contract','Amend an existing contract']:['Get a supplier or contract','Check the status of my requests','Renew or extend a contract','Make a change to a contract']
  return <section className="home"><div className="red-dash"/><p>Good morning, {flow==='business'?'John':'Catherine'}</p><h1>What would you like to do today?</h1><form className={`prompt-box ${step===1?'filled':''}`} onSubmit={e=>{e.preventDefault();onSend(text)}}><textarea aria-label="Describe what you need" value={text} onChange={e=>setText(e.target.value)} placeholder="Tell me what you need..."/><button type="button" className="attach" aria-label="Add attachment" onClick={onAttach}><Plus/></button><button className="prompt-send" type="submit" aria-label="Send request"><Send/></button></form><h3>SUGGESTED STARTS</h3><div className="suggestions">{suggestions.map((item,i)=><button onClick={()=>{setText(item);onSend(item)}} key={item}><span>{[<Users/>,<MessageSquare/>,<Clock3/>,<Pencil/>][i]}</span>{item}<ChevronRight/></button>)}</div><h2>My activity</h2><div className="activity">{[['2','My review tasks'],['1','Approvals to review'],['2','Waiting for my input'],['2','Upcoming renewals'],['1','Waiting on others']].map(([n,label])=><button key={label} onClick={()=>onSend(label)}><b>{n}</b><span>{label}</span></button>)}</div></section>
}

function Conversation({flow,step,go,request,setRequest,documents,setDocuments,messages,onSend,notify}:{flow:Flow;step:number;go:(v:number)=>void;request:RequestData;setRequest:(v:RequestData)=>void;documents:string[];setDocuments:(v:string[])=>void;messages:ChatMessage[];onSend:(v:string)=>void;notify:(v:string)=>void}){
  const [message,setMessage]=useState('');const submit=()=>{if(!message.trim())return;onSend(message);setMessage('')}
  return <section className="conversation"><header><h1>{flow==='business'?'New contract request':flow==='manager'?'Review request':'REQ-2026-0187'}</h1></header>{flow==='business'&&<Business step={step} go={go} request={request} setRequest={setRequest}/>} {flow==='manager'&&<Manager step={step} go={go} request={request} setRequest={setRequest} documents={documents} setDocuments={setDocuments} notify={notify}/>} {flow==='procurement'&&<Procurement step={step} go={go} request={request} setRequest={setRequest}/>}<ChatHistory messages={messages}/><form className="composer" onSubmit={e=>{e.preventDefault();submit()}}><button type="button" aria-label="Add attachment" onClick={()=>flow==='manager'?go(4):notify('Attachment option opened')}><Plus/></button><input aria-label="Message" value={message} onChange={e=>setMessage(e.target.value)} placeholder="Type your answer or say what you want to change..."/><button className="send" type="submit" aria-label="Send message"><Send/></button></form></section>
}
function ChatHistory({messages}:{messages:ChatMessage[]}){return messages.length?<div className="chat-history" aria-live="polite">{messages.map(m=>m.author==='user'?<div className="user-bubble" key={m.id}>{m.text}</div>:<div className="ai-message" key={m.id}><span>AI</span><p>{m.text}</p></div>)}</div>:null}

function Business({step,go,request,setRequest}:{step:number;go:(v:number)=>void;request:RequestData;setRequest:(v:RequestData)=>void}){
  if(step<=3)return <><p>Good morning, John.<br/>I can help you create a new contract. To get started, I’ll ask a few questions.</p><Question title="What type of contract do you need?" options={['New supplier','Amend existing contract','Renewal','Other']} value={request.requestType} onChange={v=>setRequest({...request,requestType:v})}/><Question title="What goods or services will the supplier provide?"/><UserBubble>{request.service} for our France offices.</UserBubble><Question title="In which country or region will the services be provided?" options={['France','EMEA (multiple countries)','Global','Other']} value={request.location} onChange={v=>setRequest({...request,location:v})}/><Question title="About how many employees will use the service?" options={['1-50','51-250','251-500','501-1,000','More than 1,000']} value={request.employees.replace('~','')} onChange={v=>setRequest({...request,employees:v})}/><Question title="When do you need the contract to be in place?" options={['Within 1 month','1-3 months','3-6 months','6-12 months','Later']} value="6-12 months" onChange={()=>{}}/><div className="actions"><button className="primary" onClick={()=>go(4)}>Continue</button></div></>
  if(step===6)return <><p>Select any field and update the request information.</p><EditForm initial={request} onSave={v=>{setRequest(v);go(5)}} onDiscard={()=>go(5)}/></>
  if(step>=7)return <><UserBubble>Everything looks good. Please submit the request.</UserBubble><RequestCard title={step===7?'Confirm and submit':'Your request has been submitted'} status={step===7?'Ready':'Submitted'} request={request} documents={[]}/><div className="notice success"><CircleCheck/><div><b>{step===7?'Ready to submit':'Your request has been submitted'}</b><p>{step===7?'Please confirm the information above.':'Request REQ-2026-0187 has been routed for review.'}</p></div></div><div className="actions">{step===7?<><button onClick={()=>go(6)}>Make a change</button><button className="primary" onClick={()=>go(8)}>Submit request</button></>:<button className="primary" onClick={()=>go(8)}>View request details</button>}</div></>
  return <><p>Great. I’ve prepared a draft request based on the information you provided. Please review the details below.</p><RequestCard title="Draft request" status={step===4?'Draft':'Updated'} request={request} documents={[]}/>{step===5&&<><UserBubble>Looks good. Please add a note that the contract should include 24/7 support.</UserBubble><p>I’ve added the note. Here is the updated draft for your review.</p></>}<div className="actions"><button onClick={()=>go(6)}>Edit information</button><button className="primary" onClick={()=>go(7)}>{step===4?'Looks good':'Continue'}</button></div></>
}

function Manager({step,go,request,setRequest,documents,setDocuments,notify}:{step:number;go:(v:number)=>void;request:RequestData;setRequest:(v:RequestData)=>void;documents:string[];setDocuments:(v:string[])=>void;notify:(v:string)=>void}){
  if(step<=3)return <><p>John Dupont has submitted a new supplier request for travel management services.<br/>I’ve reviewed the available information. Please check the key details below.</p><RequestCard title="REQ-2026-0187" status="Pending review" request={request} documents={documents}/><div className="review-points"><Sparkles/><div><b>Key points for your review</b><ol><li>This is a new supplier request. No supplier has been selected yet.</li><li>Employee personal data is involved, so <b>Privacy and Security</b> reviews will be required.</li><li>Please confirm the request is complete and correctly routed to Procurement.</li></ol></div></div><div className="actions"><button className="primary" onClick={()=>go(4)}>Send to Procurement</button><button onClick={()=>notify('Information request sent to John Dupont')}>Request more information</button><button onClick={()=>notify('Request escalated for review')}>Escalate</button><button onClick={()=>go(7)}>More options</button></div></>
  if(step===4)return <><p>Add supporting documents before sending the request to Procurement.</p><Documents documents={documents} onAdd={()=>setDocuments([...documents,`Supporting_Document_${documents.length+1}.pdf`])} onRemove={name=>setDocuments(documents.filter(v=>v!==name))}/><div className="actions"><button className="primary" onClick={()=>go(5)}>Continue</button><button onClick={()=>go(7)}>Make another change</button></div></>
  if(step===7)return <><p>What do you want to edit?</p><EditForm initial={request} onSave={v=>{setRequest(v);go(5)}} onDiscard={()=>go(3)}/></>
  return <><div className="notice success"><CircleCheck/><div><b>{step===5?'Ready to send to Procurement':'Request sent to Procurement'}</b><p>{step===5?'The request is complete and meets the required information for sourcing.':'The request has been successfully transferred to the Procurement team.'}</p></div></div><RequestCard title="New supplier request" status={step===5?'Ready':'In procurement'} request={request} documents={documents}/><div className="actions">{step===5?<><button onClick={()=>go(7)}>Make another change</button><button className="primary" onClick={()=>go(6)}>Send to Procurement</button></>:<><button onClick={()=>go(7)}>Edit request</button><button className="primary" onClick={()=>go(6)}>View request status</button></>}</div></>
}

function Procurement({step,go,request,setRequest}:{step:number;go:(v:number)=>void;request:RequestData;setRequest:(v:RequestData)=>void}){
  if(step<=3)return <><p>REQ-2026-0187 has been reviewed by Catherine Moreau and is ready for sourcing.</p><RequestCard title="New supplier request" status="Ready for sourcing" request={request} documents={['Travel_Policy.pdf','Approval_Email.pdf']}/><UserBubble>Yes, please prepare the sourcing case.</UserBubble><div className="analysis-card"><span className="loader"/><div><b>{step===3?'Analysis complete':'Analysing request...'}</b><p>Reviewing request details · Checking required inputs · Preparing sourcing plan</p></div></div><div className="actions"><button onClick={()=>go(4)}>Edit request</button><button className="primary" onClick={()=>go(step===3?6:3)}>{step===3?'Continue sourcing review':'Prepare sourcing case'}</button></div></>
  if(step===4)return <><p>Edit information</p><EditForm initial={request} onSave={v=>{setRequest(v);go(5)}} onDiscard={()=>go(3)}/></>
  if(step===5)return <><div className="notice success"><CircleCheck/><div><b>Saved successfully</b><p>The sourcing information has been updated.</p></div></div><RequestCard title="New supplier request" status="Saved" request={request} documents={['Travel_Policy.pdf','Approval_Email.pdf']}/><div className="actions"><button onClick={()=>go(4)}>Edit again</button><button className="primary" onClick={()=>go(6)}>Continue review</button></div></>
  if(step===6)return <><p>I’ve reviewed the request. Complete the sourcing information below.</p><SourcingForm request={request} onSave={v=>{setRequest(v);go(7)}} onReview={()=>go(3)}/></>
  return <><p>{step===7?'Please confirm that you want to send this request now.':'The request has been sent to Procurement for sourcing.'}</p><RequestCard title="Ready to send to Procurement" status={step===8?'Sent':'Pending review'} request={request} documents={['Travel_Policy.pdf','Approval_Email.pdf']}/><div className="notice"><Info/><div><b>What happens next?</b><p>The Procurement team will run supplier selection and coordinate the required risk reviews.</p></div></div><div className="actions">{step===7?<><button onClick={()=>go(4)}>Make another change</button><button className="primary" onClick={()=>go(8)}>Send to Procurement</button></>:<><button onClick={()=>go(8)}>View request status</button><button className="primary" onClick={()=>go(4)}>Add a note</button></>}</div></>
}

function Question({title,options=[],value,onChange}:{title:string;options?:string[];value?:string;onChange?:(v:string)=>void}){return <div className="question"><p>{title}</p>{options.length>0&&<div>{options.map(option=><button type="button" className={option===value?'selected':''} onClick={()=>onChange?.(option)} key={option}>{option}</button>)}</div>}</div>}
function UserBubble({children}:{children:React.ReactNode}){return <div className="user-bubble">{children}</div>}
function RequestCard({title,status,request,documents}:{title:string;status:string;request:RequestData;documents:string[]}){return <article className="request-card"><header><span><FileText/><b>{title}</b><small>{request.requestType}</small></span><em>{status}</em></header><div className="detail-grid">{requestRows(request).map(row=><div key={row.label}><b>{row.label}</b><span>{row.value}</span>{row.sub&&<small>{row.sub}</small>}</div>)}</div>{documents.length>0&&<footer><Paperclip/><b>Supporting documents ({documents.length})</b><span>{documents.join(', ')}</span><ChevronRight/></footer>}</article>}

function EditForm({initial,onSave,onDiscard}:{initial:RequestData;onSave:(v:RequestData)=>void;onDiscard:()=>void}){const [draft,setDraft]=useState({...initial});const update=(key:keyof RequestData,value:string)=>setDraft(v=>({...v,[key]:value}));return <form className="edit-form" onSubmit={e=>{e.preventDefault();onSave(draft)}}><h2>Edit information</h2><label>Request type<select value={draft.requestType} onChange={e=>update('requestType',e.target.value)}><option>New supplier</option><option>Amend existing contract</option><option>Renewal</option></select></label><label>Service<input value={draft.service} onChange={e=>update('service',e.target.value)} required/></label><label>Location<input value={draft.location} onChange={e=>update('location',e.target.value)} required/></label><label>Number of employees<input value={draft.employees} onChange={e=>update('employees',e.target.value)} required/></label><label>Target start date<input type="date" value={draft.targetDate} onChange={e=>update('targetDate',e.target.value)} required/></label><label>Employee personal data<select value={draft.personalData} onChange={e=>update('personalData',e.target.value)}><option>Yes</option><option>No</option><option>Not sure</option></select></label><label className="wide">Personal data details<textarea value={draft.personalDataDetail} onChange={e=>update('personalDataDetail',e.target.value)}/></label><label className="wide">Additional notes<textarea value={draft.notes} onChange={e=>update('notes',e.target.value)}/></label><div className="actions"><button type="button" onClick={onDiscard}>Discard</button><button className="primary" type="submit">Save changes</button></div></form>}

function Documents({documents,onAdd,onRemove}:{documents:string[];onAdd:()=>void;onRemove:(v:string)=>void}){return <div className="documents"><h2>Supporting documents ({documents.length})</h2>{documents.map((name,i)=><div key={name}><FileText/><span><b>{name}</b><small>{i?'1.3 MB':'2.4 MB'} • Internal document</small></span><button aria-label={`Remove ${name}`} onClick={()=>onRemove(name)}><X/></button></div>)}<button onClick={onAdd}><Paperclip/> Add another document</button></div>}

function SourcingForm({request,onSave,onReview}:{request:RequestData;onSave:(v:RequestData)=>void;onReview:()=>void}){const [draft,setDraft]=useState({...request});const items:Array<[keyof RequestData,LucideIcon,string,string]>=[['budget',CircleDollarSign,'Budget / commercial range','Estimated annual value or range'],['criteria',ListChecks,'Evaluation criteria','Price, service, implementation, security'],['deadline',CalendarDays,'Supplier response deadline','Proposed date for supplier submissions'],['notes',Info,'Additional requirements','Sustainability, local presence, diverse suppliers']];return <form className="info-needed" onSubmit={e=>{e.preventDefault();onSave(draft)}}><h2><Search/> Information needed</h2>{items.map(([key,Icon,label,hint])=><label key={key}><Icon/><span><b>{label}</b><small>{hint}</small><input type={key==='deadline'?'date':'text'} value={draft[key]} onChange={e=>setDraft(v=>({...v,[key]:e.target.value}))} required/></span></label>)}<div className="actions"><button type="button" onClick={onReview}>Review details first</button><button className="primary" type="submit">Confirm and continue</button></div></form>}

function Overview({flow,step,request,documents,onClose,onEdit,onOpenRequest}:{flow:Flow;step:number;request:RequestData;documents:string[];onClose:()=>void;onEdit:()=>void;onOpenRequest:()=>void}){const compact=flow==='business'&&step<=3;return <aside className="overview"><header><h2>Overview</h2><button aria-label="Close overview" onClick={onClose}><PanelLeftClose/></button></header><div className="overview-title"><FileText/><button className="overview-link" onClick={onOpenRequest}><b>{flow==='business'?'New request':'REQ-2026-0187'}</b><small>New supplier request</small></button><em>{step>=8?'Submitted':step>=5?'Draft':'Pending review'}</em><button aria-label="Edit request" onClick={onEdit}><Pencil/></button></div>{requestRows(request).slice(0,compact?6:7).map(row=><div className="overview-row" key={row.label}><b>{row.label}</b><span>{row.value}</span>{row.sub&&<small>{row.sub}</small>}</div>)}{documents.length>0&&<button className="overview-documents" onClick={onOpenRequest}><Paperclip/> Documents ({documents.length}) <ChevronRight/></button>}{flow!=='business'&&<Checklist flow={flow} step={step} onView={onOpenRequest}/>}<div className="overview-help"><Info/><div><b>{flow==='business'?'Need to make a change?':'AI recommendation'}</b><p>{flow==='business'?'Use Edit or tell me what to change in the chat.':'Review the required items and confirm the sourcing route.'}</p><button onClick={onEdit}>Edit information</button></div></div></aside>}
function Checklist({flow,step,onView}:{flow:Flow;step:number;onView:()=>void}){const items=flow==='manager'?['Request information','Supporting documents','Ownership and contract type','Existing supplier or contract checked','Risk, privacy and security identified']:['Submitted by Business User','Reviewed and approved by Contract Manager','Ready for sourcing','Supplier selection','Risk, privacy and security identified','Evaluation'];const completed=step>5?3:2;return <div className="checklist"><header><b>Review checklist</b><button onClick={onView}>View all</button></header>{items.map((item,i)=><button className={i<completed?'done':i===completed?'current':''} onClick={onView} key={item}><i>{i<completed&&<Check/>}</i><span><b>{item}</b><small>{i<completed?'Complete':i===completed?'With Procurement':'Needs review'}</small></span></button>)}</div>}

function requestRows(request:RequestData){return[{label:'Request type',value:request.requestType},{label:'Service',value:request.service},{label:'Location',value:request.location},{label:'Number of employees',value:request.employees},{label:'Target start date',value:formatDate(request.targetDate)},{label:'Employee personal data',value:request.personalData,sub:request.personalDataDetail},{label:'Additional notes',value:request.notes}]}
function formatDate(value:string){const date=new Date(`${value}T00:00:00`);return Number.isNaN(date.getTime())?value:new Intl.DateTimeFormat('en-GB',{day:'numeric',month:'long',year:'numeric'}).format(date)}
createRoot(document.getElementById('root')!).render(<React.StrictMode><App/></React.StrictMode>)
